import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#1a2b3c' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 },
  logo: { width: 90, height: 50, objectFit: 'contain' },
  companyName: { fontSize: 14, fontWeight: 700, color: '#0F2540' },
  companySub: { fontSize: 8, color: '#6b7280', marginTop: 2 },
  docTitle: { fontSize: 18, fontWeight: 700, color: '#0F2540', textAlign: 'right' },
  docMeta: { fontSize: 9, color: '#6b7280', textAlign: 'right', marginTop: 2 },
  row: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottom: '0.5pt solid #e5e7eb' },
  checkbox: { width: 14, height: 14, border: '1.2pt solid #0F2540', borderRadius: 2, marginRight: 12 },
  itemName: { fontSize: 11, color: '#1a2b3c', flex: 1 },
  itemQty: { fontSize: 10, color: '#6b7280' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#9ca3af', textAlign: 'center', borderTop: '0.5pt solid #e5e7eb', paddingTop: 8 },
  signLine: { marginTop: 30, paddingTop: 12, borderTop: '0.5pt solid #d1d5db' },
  signLabel: { fontSize: 8, color: '#9ca3af' },
})

export function ChecklistDocument({ company, template, items }) {
  const categoryLabel = { trip_check: 'Trip / Vehicle Checklist', room_inventory: 'Room Inventory', general: 'Checklist' }[template.category] || 'Checklist'

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerRow}>
          <View>
            {company.logo_url ? <Image src={company.logo_url} style={styles.logo} /> : <Text style={styles.companyName}>{company.name}</Text>}
            {company.logo_url && <Text style={[styles.companySub, { marginTop: 6, fontWeight: 700, color: '#0F2540', fontSize: 11 }]}>{company.name}</Text>}
          </View>
          <View>
            <Text style={styles.docTitle}>{template.name}</Text>
            <Text style={styles.docMeta}>{categoryLabel}</Text>
            <Text style={styles.docMeta}>Generated {new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' })}</Text>
          </View>
        </View>

        {items.length === 0 ? (
          <Text style={{ color: '#9ca3af' }}>No items on this list yet.</Text>
        ) : (
          <View>
            {items.map(item => (
              <View style={styles.row} key={item.id}>
                <View style={styles.checkbox} />
                <Text style={styles.itemName}>{item.name}</Text>
                {item.quantity ? <Text style={styles.itemQty}>x{item.quantity}</Text> : null}
              </View>
            ))}
          </View>
        )}

        <View style={styles.signLine}>
          <Text style={styles.signLabel}>Checked by: _______________________        Date: _______________</Text>
        </View>

        <Text style={styles.footer} fixed>
          {company.name} · Generated by OpDesk
        </Text>
      </Page>
    </Document>
  )
}
