import { createClient } from '@/lib/supabase/server'

export async function getInvoiceData(invoiceId) {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  // Fetch the invoice by ID alone first, then derive its company from the
  // invoice itself rather than the viewer's own profile.company_id — a
  // superadmin viewing an invoice outside their own company (e.g. one of
  // OpDesk's own internal invoices) has no matching profile.company_id at
  // all, so filtering on that would incorrectly say "not found" even
  // though RLS's own is_superadmin() bypass already allows the read. A
  // normal tenant user gets exactly the same result as before, since RLS
  // still restricts them to their own company's invoices either way.
  const { data: invoice, error: invErr } = await supabase.from('invoices').select('*').eq('id', invoiceId).maybeSingle()
  if (invErr || !invoice) throw new Error('Invoice not found')

  const { data: company } = await supabase.from('companies').select('*').eq('id', invoice.company_id).maybeSingle()
  if (!company) throw new Error('Company not found for this invoice')

  const { data: payments } = await supabase.from('invoice_payments').select('*').eq('invoice_id', invoiceId).order('payment_date')

  // Buying the HR or Logistics add-on removes the "Generated by OpDesk"
  // line from the footer, regardless of core tier — a value-add for those
  // two bundles specifically, not a general tier perk.
  const { data: addons } = await supabase.from('company_addons').select('addon_key').eq('company_id', invoice.company_id).eq('active', true)
  const noWatermark = (addons || []).some(a => a.addon_key === 'hr_bundle' || a.addon_key === 'logistics_bundle')

  return { company, invoice, payments: payments || [], noWatermark }
}
