import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  coverPage: { padding: 40, fontFamily: 'Helvetica', color: '#1a2b3c', justifyContent: 'center', alignItems: 'center' },
  coverLogo: { width: 160, height: 90, objectFit: 'contain', marginBottom: 24 },
  coverCompanyName: { fontSize: 22, fontWeight: 700, color: '#0F2540', textAlign: 'center' },
  coverTitle: { fontSize: 14, color: '#6b7280', marginTop: 8, textAlign: 'center' },
  coverDate: { fontSize: 9, color: '#9ca3af', marginTop: 40, textAlign: 'center' },

  page: { padding: 40, fontSize: 10.5, fontFamily: 'Helvetica', color: '#1a2b3c' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20, paddingBottom: 10, borderBottom: '0.5pt solid #e5e7eb' },
  headerCompany: { fontSize: 9, color: '#6b7280' },
  headerDoc: { fontSize: 9, color: '#6b7280' },
  sectionTitle: { fontSize: 14, fontWeight: 700, color: '#0F2540', marginBottom: 10 },
  paragraph: { fontSize: 10.5, color: '#1a2b3c', lineHeight: 1.6, marginBottom: 8 },
  footer: { position: 'absolute', bottom: 24, left: 40, right: 40, fontSize: 8, color: '#9ca3af', textAlign: 'center' },
})

export function HandbookDocument({ company, sections, noWatermark }) {
  const today = new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' })

  return (
    <Document>
      {/* Cover page */}
      <Page size="A4" style={styles.coverPage}>
        {company.logo_url ? (
          <Image src={company.logo_url} style={styles.coverLogo} />
        ) : (
          <Text style={styles.coverCompanyName}>{company.name}</Text>
        )}
        {company.logo_url && <Text style={styles.coverCompanyName}>{company.name}</Text>}
        <Text style={styles.coverTitle}>Company Handbook — Rules &amp; Procedures</Text>
        <Text style={styles.coverDate}>Generated {today}</Text>
      </Page>

      {/* One page per section — keeps each policy self-contained and easy
          to reprint or replace individually without reflowing the rest. */}
      {sections.map(s => (
        <Page key={s.id} size="A4" style={styles.page}>
          <View style={styles.headerRow}>
            <Text style={styles.headerCompany}>{company.name} — Company Handbook</Text>
            <Text style={styles.headerDoc}>{today}</Text>
          </View>
          <Text style={styles.sectionTitle}>{s.title}</Text>
          {(s.content || '').split(/\n{2,}/).map((para, i) => (
            <Text key={i} style={styles.paragraph}>{para}</Text>
          ))}
          <Text style={styles.footer} fixed>
            {company.name}{!noWatermark && ' · Generated by OpDesk'}
          </Text>
        </Page>
      ))}
    </Document>
  )
}
