// Per-feature content for the /features/[slug] SEO landing pages. Each
// entry drives both the page content and its <head> metadata (title,
// description, keywords) — this is the actual SEO surface area: 18
// individually-targetable pages instead of one page listing everything,
// each aimed at the specific search terms an operator would actually type.

export const FEATURES_CONTENT = {
  'bookings-calendar': {
    group: 'Operations', icon: 'bookingCalendar',
    title: 'Bookings & Calendar',
    metaTitle: 'Booking & Calendar Software for Tour and Safari Operators',
    metaDescription: 'Manage tour, transfer, charter and accommodation bookings in one shared calendar. Built for safari lodges, shuttle companies, and African tourism operators.',
    keywords: ['booking software for safari lodges', 'tour operator booking system', 'safari booking calendar', 'shuttle booking software', 'charter booking management', 'tourism booking software Africa'],
    heroTagline: 'One calendar for every booking, every operator type',
    intro: 'Stop juggling a paper diary, a WhatsApp group, and three spreadsheets. OpDesk gives every booking — tour, transfer, charter, or overnight stay — one shared calendar your whole team can see, with guest details, pricing, and status tracked against each date.',
    benefits: [
      'Click any day to see, add, or edit bookings for that date',
      'Assign a guide, driver, vehicle, or room to a booking as you create it',
      'Track guest count, contact details, and special requirements per booking',
      'Status tracking from pending through confirmed to completed',
      'No double-bookings — see what\u2019s already committed before you confirm a new one',
    ],
    forWhom: 'Safari lodges, shuttle and transfer companies, fishing and yacht charters, trail guides, and guesthouses managing bookings across multiple resources.',
  },
  'fleet-management': {
    group: 'Operations', icon: 'fleet',
    title: 'Fleet Management',
    metaTitle: 'Vehicle & Fleet Management Software for Safari and Shuttle Operators',
    metaDescription: 'Track game vehicles, shuttles, and transfer vehicles — registration, capacity, licence and insurance expiry — in one fleet management dashboard.',
    keywords: ['fleet management software safari', 'game vehicle tracking software', 'shuttle fleet management', 'vehicle licence expiry tracker', 'transport operator fleet software'],
    heroTagline: 'Every vehicle, its status, and what\u2019s due for renewal',
    intro: 'A missed licence renewal or an overdue service can shut a vehicle down mid-season. OpDesk keeps your entire fleet — game vehicles, shuttles, transfer vans — in one place, with registration, capacity, and status always visible before you assign it to a booking.',
    benefits: [
      'Track registration, make, model, year, and seating capacity per vehicle',
      'See at a glance which vehicles are available, in use, or in for maintenance',
      'Assign vehicles directly to bookings from the calendar or booking form',
      'Separate tracking for vehicles and vessels (boats, charter vessels)',
      'Fleet visibility that scales from 1 vehicle to an unlimited fleet on higher plans',
    ],
    forWhom: 'Safari operators, shuttle and transfer companies, and any operator running their own vehicles rather than relying on third-party transport.',
  },
  'trails-module': {
    group: 'Operations', icon: 'trailsModule',
    title: 'Trails Module',
    metaTitle: 'Trail Management Software for Hiking & Adventure Guides',
    metaDescription: 'Manage trail routes, difficulty ratings, distance, duration, and guide assignments for hiking and adventure tour operators.',
    keywords: ['trail guide software', 'hiking tour management software', 'adventure operator trail tracking', 'trail route management system'],
    heroTagline: 'Routes, difficulty, and guide assignments in one place',
    intro: 'Trail operators juggle a different kind of complexity than a lodge or shuttle company — routes, difficulty ratings, group capacity, and which guide knows which trail. The Trails module keeps all of it organized and linked directly to your bookings.',
    benefits: [
      'Record distance, duration, and difficulty rating per trail',
      'Set maximum group size (max pax) per route',
      'Log start and end points, highlights, and GPX route files',
      'Assign guides to trails based on who\u2019s qualified and available',
      'Link trail bookings straight into your main booking calendar',
    ],
    forWhom: 'Trail guiding and adventure tourism operators running hiking, walking safari, or multi-day trail experiences.',
  },
  'shifts-scheduling': {
    group: 'Operations', icon: 'schedules',
    title: 'Shifts & Scheduling',
    metaTitle: 'Staff Shift Scheduling Software for Tourism & Hospitality Operators',
    metaDescription: 'Roster guides, drivers, and support staff against bookings so nothing gets double-booked. Shift scheduling built for tourism and hospitality teams.',
    keywords: ['staff scheduling software tourism', 'guide roster software', 'shift scheduling hospitality', 'employee rostering safari lodge'],
    heroTagline: 'Roster your team without double-booking anyone',
    intro: 'Assigning a guide to two departures on the same morning is an easy mistake to make when your roster lives in someone\u2019s head or a WhatsApp thread. The Shifts module gives every staff member a schedule tied directly to your bookings and time slots.',
    benefits: [
      'Schedule shifts by date, start/end time, and shift type (morning, full-day, night)',
      'Assign a role per shift — guide, driver, housekeeping, front desk',
      'Track shift status from scheduled through confirmed to completed',
      'See who\u2019s rostered before you commit them to a new booking',
      'Included from Standard plans upward, or available as an add-on',
    ],
    forWhom: 'Any operator with a team of guides, drivers, or hospitality staff working shifts against a booking calendar.',
  },
  'staff-roles': {
    group: 'Staff & HR', icon: 'teamRoles',
    title: 'Staff & Roles',
    metaTitle: 'Staff Management Software with Role-Based Access for Tourism Operators',
    metaDescription: 'A full staff directory with employment type, contact details, and role-based access — built for safari, shuttle, and hospitality teams.',
    keywords: ['staff management software tourism', 'employee directory hospitality software', 'role based access tour operator', 'HR software safari lodge'],
    heroTagline: 'One directory for your whole team, with the right access for each role',
    intro: 'From owner to guide to housekeeping, everyone on your team needs different access — and you need one place to see who\u2019s on staff, how they\u2019re employed, and how to reach them. Staff & Roles is the foundation the rest of OpDesk\u2019s HR tools build on.',
    benefits: [
      'Full staff directory with contact details and employment type (full-time, part-time, seasonal, contract)',
      'Role-based access so front desk staff and owners see different things',
      'Active/inactive status tracking as your team changes',
      'The base staff record every certification, shift, leave, and payroll entry links back to',
      'Included on every plan, from Free upward',
    ],
    forWhom: 'Every operator with more than one person on the team — this is core functionality, not a premium add-on.',
  },
  'certifications': {
    group: 'Staff & HR', icon: 'guides',
    title: 'Certifications',
    metaTitle: 'Guide Certification Tracking Software with Expiry Alerts',
    metaDescription: 'Track FGASA, PDP, skippers tickets, first aid and other guide certifications with expiry alerts — never send an unqualified guide into the field.',
    keywords: ['guide certification tracking software', 'FGASA certification tracker', 'PDP expiry tracking', 'skippers ticket management', 'guide qualification software South Africa'],
    heroTagline: 'Never let a certification expire without you knowing',
    intro: 'A guide with a lapsed FGASA qualification or an expired PDP isn\u2019t just a compliance risk — in some jurisdictions it\u2019s a legal one. Certifications tracks every staff qualification against its expiry date and flags anything expiring soon before it becomes a problem.',
    benefits: [
      'Track certification type, number, issuing body, issue date, and expiry date',
      'Color-coded status: valid, expiring within 30 days, or expired',
      'Cover FGASA, PDP, skippers tickets, first aid, firearm competency, and more',
      'One record per staff member, all certifications in one view',
      'Included from Professional plans, or available as an individual add-on',
    ],
    forWhom: 'Safari operators, fishing and yacht charters, and trail guides — anywhere a lapsed qualification is a real operational or legal risk.',
  },
  'firearm-register': {
    group: 'Staff & HR', icon: 'firearmRegister',
    title: 'Firearm Register',
    metaTitle: 'Firearm Register Software for Safari and Fishing Operators',
    metaDescription: 'Compliant firearm tracking for safari and fishing operators — serial numbers, licences, and safe storage locations, with licence expiry alerts.',
    keywords: ['firearm register software safari', 'firearm licence tracking system', 'safari rifle register', 'firearm compliance software South Africa'],
    heroTagline: 'Every firearm, its licence, and where it\u2019s stored',
    intro: 'Firearms used on safari or during anti-poaching operations come with serious compliance obligations. The Firearm Register keeps make, model, calibre, serial number, licence number and expiry, and safe storage location all in one auditable record.',
    benefits: [
      'Record make, model, calibre, and serial number per firearm',
      'Track licence number and expiry date with renewal alerts',
      'Log safe storage location for compliance audits',
      'Link firearms to the staff member responsible for them',
      'Status tracking — stored, in use, in for service',
    ],
    forWhom: 'Safari operators and fishing charters with firearms on the premises for guiding or anti-poaching purposes.',
  },
  'cost-to-company': {
    group: 'Staff & HR', icon: 'driversShuttles',
    title: 'Cost to Company',
    metaTitle: 'Payroll & Cost-to-Company Software for Tourism Operators',
    metaDescription: 'Full payroll breakdowns — salary, allowances, deductions, UIF, PAYE — with true cost-to-company per staff member, calculated automatically.',
    keywords: ['cost to company calculator software', 'payroll software small business South Africa', 'UIF PAYE payroll tracking', 'staff cost tracking tourism operator'],
    heroTagline: 'Know what every staff member really costs you',
    intro: 'Basic salary is only part of the story — housing and transport allowances, UIF, PAYE, medical aid contributions on both sides all add up to what a staff member actually costs. Cost to Company calculates gross salary, total deductions, net take-home, and true cost to company automatically from what you enter.',
    benefits: [
      'Record basic salary plus housing, transport, and meal allowances',
      'Track employee deductions: UIF, PAYE, medical aid, other',
      'Track employer contributions: UIF, medical aid',
      'Gross salary, net take-home, and cost-to-company calculated automatically',
      'Included from Enterprise plans, or available as an individual add-on',
    ],
    forWhom: 'Any operator who wants a real picture of staff cost beyond basic salary — particularly useful once you\u2019re managing more than a handful of employees.',
  },
  'lodging-rooms': {
    group: 'Guest & Property', icon: 'gameLodge',
    title: 'Lodging & Rooms',
    metaTitle: 'Room Management Software for Lodges, Guesthouses & Hotels',
    metaDescription: 'Room inventory, nightly rates, and live occupancy status for lodges, guesthouses, hotels, and campsites — including tented camps and campsite pitches.',
    keywords: ['room management software lodge', 'hotel room inventory system', 'guesthouse booking software', 'campsite management software', 'lodge occupancy tracking'],
    heroTagline: 'Every room, its rate, and whether it\u2019s occupied tonight',
    intro: 'Whether you run 3 rooms or 300, you need one clear view of what\u2019s available, what\u2019s occupied, and what each room earns per night. Lodging & Rooms covers every accommodation type — from single rooms and suites to tented camps and campsite pitches, small or large.',
    benefits: [
      'Track room type, floor, capacity, and nightly rate per room',
      'Room types include single, double, twin, family, suite, chalet, luxury tent, tented camp, and small or large campsite',
      'Live status: available, occupied, or under maintenance',
      'See occupancy at a glance from the room overview dashboard',
      'Room limits scale with your plan — from 1 room free up to unlimited',
    ],
    forWhom: 'Airbnb and homestay hosts, guesthouses, lodges and camps, and hotels or motels of any size.',
  },
  'housekeeping': {
    group: 'Guest & Property', icon: 'shuttle',
    title: 'Housekeeping',
    metaTitle: 'Housekeeping & Room Turnover Software for Hospitality Operators',
    metaDescription: 'Assign and track room cleaning, turnover, and maintenance tasks so every room is guest-ready on schedule.',
    keywords: ['housekeeping management software', 'room turnover tracking system', 'hotel cleaning task software', 'hospitality task board'],
    heroTagline: 'Every room task, tracked from pending to done',
    intro: 'A guest arriving to an unmade room is one of the fastest ways to lose a good review. Housekeeping gives your team a clear task board — pending, in progress, completed — for cleaning, turnover, inspection, and maintenance requests, assigned to whoever\u2019s on shift.',
    benefits: [
      'Task types: full clean, guest turnover, inspection, and maintenance requests',
      'Assign tasks to specific staff members with a scheduled time',
      'Simple three-column board: pending, in progress, completed',
      'Linked directly to your room inventory',
      'Included on every plan — core hospitality functionality, not a paid add-on',
    ],
    forWhom: 'Any lodging operator with rooms to turn over between guests — lodges, guesthouses, hotels, and camps.',
  },
  'guest-directory': {
    group: 'Guest & Property', icon: 'islandTransfer',
    title: 'Guest Directory',
    metaTitle: 'Guest Directory Software for Repeat Guest Tracking',
    metaDescription: 'A single view of every guest across all your stays and bookings — built for lodges, hotels, and tour operators who want to recognize repeat guests.',
    keywords: ['guest management software hotel', 'repeat guest tracking system', 'guest directory lodge software', 'CRM for tourism operators'],
    heroTagline: 'Recognize a returning guest before they have to remind you',
    intro: 'A guest who\u2019s stayed with you three times shouldn\u2019t have to re-explain their preferences every time. The Guest Directory pulls every booking a guest has made — across rooms, tours, or transfers — into one view, so your team always has the full history at hand.',
    benefits: [
      'One record per guest across every booking type',
      'Full stay and booking history in one place',
      'Contact details and nationality tracked per guest',
      'Foundation for guest recognition and repeat-business follow-up',
    ],
    forWhom: 'Lodges, hotels, and tour operators who want to build a relationship with repeat guests rather than treating every booking as a first-time visitor.',
  },
  'invoicing': {
    group: 'Finance & Reporting', icon: 'proformaInvoice',
    title: 'Pro Forma & Tax Invoices',
    metaTitle: 'Invoicing Software for Tour Operators with Multi-Currency VAT',
    metaDescription: 'Generate professional pro forma and tax invoices with automatic VAT calculation in your local currency — ZAR, KES, USD and more.',
    keywords: ['invoicing software tour operator', 'pro forma invoice generator Africa', 'tax invoice software VAT', 'multi-currency invoicing tourism'],
    heroTagline: 'Professional invoices, automatic VAT, your currency',
    intro: 'Guests expect a proper invoice, and your accountant expects the VAT math to be right. Generate pro forma invoices before a trip and tax invoices after, with VAT calculated automatically in whichever of 15+ currencies you bill in.',
    benefits: [
      'Pro forma invoices for deposits and bookings, tax invoices for completed stays',
      'Automatic VAT calculation at your configured rate',
      'Bill in ZAR, KES, TZS, USD, EUR, and 10+ other currencies',
      'Line-item detail linked directly to the originating booking',
      'Track invoice status: draft, sent, paid',
    ],
    forWhom: 'Every operator who needs to invoice guests or corporate clients — included on every plan.',
  },
  'reports-analytics': {
    group: 'Finance & Reporting', icon: 'dashboardReports',
    title: 'Reports & Analytics',
    metaTitle: 'Reporting & Analytics Dashboard for Tourism and Hospitality Businesses',
    metaDescription: 'Occupancy, revenue, staff cost, and booking trend reports for tourism and hospitality operators — know your numbers without exporting to Excel.',
    keywords: ['tourism business analytics software', 'hotel occupancy reporting software', 'revenue reporting tour operator', 'hospitality dashboard software'],
    heroTagline: 'Your occupancy, revenue, and booking trends, always current',
    intro: 'Knowing whether last month was actually good or just felt good shouldn\u2019t require an afternoon in a spreadsheet. Reports & Analytics keeps occupancy, revenue, staff cost, and booking trend data live on your dashboard, whenever you need to check it.',
    benefits: [
      'Occupancy rates across rooms, vehicles, or vessels',
      'Revenue trends by period, booking type, or resource',
      'Staff cost reporting drawing on your Cost to Company data',
      'Booking trend visibility to spot your busy and slow seasons',
    ],
    forWhom: 'Any operator who wants to make decisions based on real numbers rather than gut feel.',
  },
  'csv-export': {
    group: 'Finance & Reporting', icon: 'csvExport',
    title: 'CSV Data Export',
    metaTitle: 'CSV Export Tools for Tourism Operations Data',
    metaDescription: 'Export bookings, staff, financial, and operational data to CSV for your accountant, auditor, or your own spreadsheets.',
    keywords: ['CSV export tourism software', 'operations data export tool', 'accounting export tour operator software'],
    heroTagline: 'Your data, out to a spreadsheet whenever you need it',
    intro: 'OpDesk is where your operational data lives day to day, but it\u2019s never locked in. Export bookings, staff records, financials, or any other operational data to CSV for your accountant, an audit, or your own analysis.',
    benefits: [
      'Export any module\u2019s data — bookings, staff, invoices, and more',
      'Standard CSV format opens directly in Excel or Google Sheets',
      'No lock-in — your data stays exportable at any time',
    ],
    forWhom: 'Every operator, particularly at tax time or when working with an external accountant or auditor.',
  },
  'automatic-backups': {
    group: 'Finance & Reporting', icon: 'autoBackup',
    title: 'Automatic Backups',
    metaTitle: 'Automatic Data Backup for Tourism Operations Software',
    metaDescription: 'Your operational data is automatically backed up, so a lost laptop or an accidental delete never costs you your booking history.',
    keywords: ['automatic data backup software tourism', 'cloud backup tour operator data', 'data protection hospitality software'],
    heroTagline: 'A lost laptop should never mean lost data',
    intro: 'Your booking history, guest records, and financial data are too important to live in a single spreadsheet on one computer. OpDesk backs up your operational data automatically in the cloud, so hardware failure, theft, or an accidental delete never puts your business at risk.',
    benefits: [
      'Automatic, ongoing backup with no action required from you',
      'Cloud-based storage independent of any single device',
      'Peace of mind that a lost laptop doesn\u2019t mean lost history',
    ],
    forWhom: 'Every operator — this runs quietly in the background on every plan.',
  },
  'multi-currency': {
    group: 'Platform', icon: 'multiCurrency',
    title: 'Multi-Currency & Language',
    metaTitle: 'Multi-Currency Tourism Software for African Operators',
    metaDescription: 'Run your business in ZAR, KES, TZS, USD, EUR and more, with support for English, Afrikaans, French, Swahili and other regional languages.',
    keywords: ['multi currency booking software Africa', 'ZAR KES tourism software', 'multilingual tour operator software', 'African currency invoicing software'],
    heroTagline: 'Built for how Africa actually does business',
    intro: 'A safari lodge billing in ZAR, a Kenyan tour operator in KES, a Tanzanian camp in TZS — OpDesk was built around the reality that African tourism operators work across currencies and languages, not as an afterthought bolted onto a US-first product.',
    benefits: [
      'Bill and report in ZAR, KES, TZS, BWP, NAD, USD, EUR and more',
      'Interface language support including English, Afrikaans, French, Portuguese, and Swahili',
      'Per-company currency and language settings',
    ],
    forWhom: 'Operators anywhere across Southern and East Africa, and any operator billing international guests in their home currency.',
  },
  'white-label-branding': {
    group: 'Platform', icon: 'whiteLabel',
    title: 'White-Label Branding',
    metaTitle: 'White-Label Branding for Guest-Facing Tourism Documents',
    metaDescription: 'Put your own logo and brand colours on guest-facing invoices and documents instead of a generic template.',
    keywords: ['white label invoicing software', 'custom branded invoices tourism', 'branded guest documents software'],
    heroTagline: 'Your brand on every document your guests see',
    intro: 'An invoice or booking confirmation is a touchpoint with your guest — it should look like it came from your lodge, not a generic software vendor. White-Label Branding puts your logo and brand colours on every guest-facing document.',
    benefits: [
      'Your logo on invoices, confirmations, and other guest documents',
      'Custom primary brand colour applied across guest-facing templates',
      'Available on Professional and Enterprise plans, or as an individual add-on',
    ],
    forWhom: 'Established operators who want every guest touchpoint to reinforce their own brand.',
  },
  'built-for-africa': {
    group: 'Platform', icon: 'marketing',
    title: 'Built for Africa\u2019s Operators',
    metaTitle: 'Operations Software Built Specifically for African Tourism Businesses',
    metaDescription: 'OpDesk is built around how safari lodges, shuttle companies, charters, and trail operators actually work — not a generic tool adapted after the fact.',
    keywords: ['tourism software built for Africa', 'safari lodge management system', 'African tour operator software', 'South African tourism business software'],
    heroTagline: 'Not a generic tool with Africa bolted on afterward',
    intro: 'Most operations software is built for hotels in Europe or tour companies in the US. OpDesk is built from the ground up around the operators who keep Africa\u2019s tourism industry running — firearm registers, multi-currency invoicing across a dozen African currencies, and the difference between a game vehicle and a shuttle van, all handled natively.',
    benefits: [
      'Operator types built in from day one: safari, shuttle, fishing, yacht, trail, lodging, East Africa tours, island transfers',
      'Compliance features relevant to the region — firearm registers, guide certification tracking',
      'African currencies and languages as first-class citizens, not an add-on',
      'No booking fees — a flat monthly plan, not a cut of every guest transaction',
    ],
    forWhom: 'Every operator tired of adapting a generic international tool to fit an African tourism business.',
  },
}

export const FEATURE_SLUGS = Object.keys(FEATURES_CONTENT)
